<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:ns0="saibot.airport/services/slot" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/sp/AllocateSlotsDB" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction"
                xmlns:reference="saibot.airport/data/reference" xmlns:common="saibot.airport/data/common">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../Schemas/SlotService.xsd"/>
            <oracle-xsl-mapper:rootElement name="allocateSlotRequestMessage" namespace="saibot.airport/services/slot"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../Resources/AllocateSlotsDB_sp.xsd"/>
            <oracle-xsl-mapper:rootElement name="InputParameters" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/AllocateSlotsDB"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [THU JAN 21 23:04:36 CET 2016].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:InputParameters>
         <tns:P_SLOTS>
            <tns:P_SLOTS_ITEM>
               <tns:AIRCARRIER_CODE>
                  <xsl:value-of select="/ns0:allocateSlotRequestMessage/ns0:Carrier"/>
               </tns:AIRCARRIER_CODE>
               <tns:TIMEBLOCK>
                  <tns:START_DATE>
                     <xsl:value-of select="/ns0:allocateSlotRequestMessage/ns0:TimePlanningUnit/reference:startDate"/>
                  </tns:START_DATE>
                  <tns:END_DATE>
                     <xsl:value-of select="/ns0:allocateSlotRequestMessage/ns0:TimePlanningUnit/reference:endDate"/>
                  </tns:END_DATE>
                  <tns:DAYS_OF_WEEK>
                     <xsl:for-each select="/ns0:allocateSlotRequestMessage/ns0:TimePlanningUnit/reference:DaysOfWeek/reference:day">
                        <tns:DAYS_OF_WEEK_ITEM>
                           <xsl:value-of select="substring (text(), 1, 3 )"/>
                        </tns:DAYS_OF_WEEK_ITEM>
                     </xsl:for-each>
                  </tns:DAYS_OF_WEEK>
                  <tns:HOUR_OF_DAY>
                     <xsl:value-of select="/ns0:allocateSlotRequestMessage/ns0:TimePlanningUnit/reference:HourOfDay"/>
                  </tns:HOUR_OF_DAY>
                  <tns:FIVE_MINUTE_BLOCK>
                     <xsl:value-of select="/ns0:allocateSlotRequestMessage/ns0:TimePlanningUnit/reference:FiveMinuteBlock"/>
                  </tns:FIVE_MINUTE_BLOCK>
               </tns:TIMEBLOCK>
               <tns:ARRIVAL_OR_DEPARTURE>
                  <xsl:value-of select="/ns0:allocateSlotRequestMessage/ns0:ArrivalOrDeparture"/>
               </tns:ARRIVAL_OR_DEPARTURE>
               <tns:AIRCRAFT_MODEL_IATA_CODE>
                  <xsl:value-of select="/ns0:allocateSlotRequestMessage/ns0:AircraftModel"/>
               </tns:AIRCRAFT_MODEL_IATA_CODE>
            </tns:P_SLOTS_ITEM>
         </tns:P_SLOTS>
      </tns:InputParameters>
   </xsl:template>
</xsl:stylesheet>
